eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
    profile: cloud
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
    profile: dev
eureka:
  instance:
    nonSecurePort: 8080
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
