eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


---
spring:
    profiles: dev
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:876100/eureka/


---
spring:
    profiles: dev
eureka:
  instance:
    nonSecurePort: 8081
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
---
spring:
    profiles: cloud
eureka:
  instance:
    nonSecurePort: 8083
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
